# Generated by Django 5.2.1 on 2025-05-22 05:36

import django.core.validators
import django.db.models.deletion
import media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя исполнителя')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('image', models.ImageField(blank=True, upload_to='artists/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото исполнителя')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='media_app_a_name_14512b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='media_app_c_slug_180e92_idx')],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('audio_file', models.FileField(upload_to=media_app.models.music_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Аудио файл')),
                ('cover_image', models.ImageField(blank=True, upload_to=media_app.models.cover_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Обложка')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байты)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='media_app.artist', verbose_name='Исполнитель')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_items', to='media_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Музыкальный трек',
                'verbose_name_plural': 'Музыкальные треки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='media_app_m_created_c074ca_idx'), models.Index(fields=['release_date'], name='media_app_m_release_268721_idx'), models.Index(fields=['view_count'], name='media_app_m_view_co_6b6fc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to=media_app.models.video_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Видео файл')),
                ('thumbnail', models.ImageField(blank=True, upload_to=media_app.models.thumbnail_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Превью')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байты)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_items', to='media_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='media_app_v_created_af62b0_idx'), models.Index(fields=['view_count'], name='media_app_v_view_co_fa06a0_idx')],
            },
        ),
    ]
