# Generated by Django 5.2.1 on 2025-05-23 10:57

import django.core.validators
import django.db.models.deletion
import media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание альбома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный альбом')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('photo_count', models.PositiveIntegerField(default=0, verbose_name='Количество фотографий')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_items', to='media_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фотографии')),
                ('image', models.ImageField(upload_to=media_app.models.photo_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'tiff', 'bmp'])], verbose_name='Изображение')),
                ('thumbnail', models.ImageField(blank=True, upload_to=media_app.models.photo_thumbnail_path, verbose_name='Миниатюра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата съемки')),
                ('camera_model', models.CharField(blank=True, max_length=100, verbose_name='Модель камеры')),
                ('camera_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки камеры')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='Название места')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла (байты)')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина изображения')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Высота изображения')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги (через запятую)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='media_app.album', verbose_name='Альбом')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_items', to='media_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='media_app.photo', verbose_name='Обложка альбома'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-created_at'], name='media_app_p_created_6cc7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['taken_at'], name='media_app_p_taken_a_12de89_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['view_count'], name='media_app_p_view_co_ad69d8_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['latitude', 'longitude'], name='media_app_p_latitud_8605d4_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-updated_at'], name='media_app_a_updated_d58a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['is_private'], name='media_app_a_is_priv_16b820_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['view_count'], name='media_app_a_view_co_1e9462_idx'),
        ),
    ]
